name: anyinspect_plugin_network
description: AnyInspect Network Plugin
version: 0.0.1
homepage: https://github.com/anyinspect/plugins

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  anyinspect_client: ^0.0.1

dependency_overrides:
  anyinspect_client:
    path: ../../../anyinspect/packages/anyinspect_client
  anyinspect_ui:
    path: ../../../anyinspect/packages/anyinspect_ui
